# yaml-language-server: $schema=https://json.schemastore.org/eslintrc.json
env:
  browser: true
  es2017: true
  node: true
extends:
  - slekup
  - 'plugin:svelte/recommended'
overrides:
  - files:
      - '*.svelte'
    parser: svelte-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      project:
        - './tsconfig.json'
parserOptions:
  ecmaVersion: 2020
  extraFileExtensions:
    - '.svelte'
  sourceType: 'module'
root: true
rules:
  'jsdoc/require-jsdoc': 'off'
  'no-console': 'off'
